import { describe, expect, it } from "vitest";
import { ALL_PERMS, OPEN_PERMS } from "@config/access";
import { DEFAULT_SECTIONS, FIXED_IMPLEMENTATIONS, RESERVED_SECTION_IDS, sectionPath } from "@config/jawad/sections";
import { DELIVER_KINDS, KHARQ, KHARQ_PERSONA, KHARQ_PLATFORM_RULES, KHARQ_STARTS, ROAD_IDS, findRoad, isDeliverKind, isKharqStage, roadsBlock } from "@config/kharq";
import { ANSWER_SCHEMA } from "@/lib/kharq/chat";
import { cleanHistory, findAsk, forModel, readDeliver, readMedia, readQuestions, readTable, titleOf, withAsk, type Chat, type Turn } from "@/lib/kharq/chats";
import { briefBlock, systemText } from "@/lib/kharq/persona";
import { bodyHtml, fileNameOf } from "@/lib/kharq/pdf";

describe("«محمد الخارق» — the persona", () => {
  it("is the ROCTCF builder that EMBODIES its own template instead of handing it over, and never shows its stages", () => {
    expect(KHARQ_PERSONA.length).toBeGreaterThan(3000);
    for (const line of ["أنت «محمد الخارق»", "تتقمّصه", "لا يظهر على الشاشة أبدًا", "# R — ROLE", "# O — OBJECTIVE", "# C — CONTEXT", "# T — TASK", "# C — CONSTRAINTS", "# F — FORMAT"]) {
      expect(KHARQ_PERSONA, line).toContain(line);
    }
    // the five stages of the owner's builder are all there, and all his own, not the person's
    for (const line of ["الفهم والأسئلة", "استكمال النقص", "القالب والتقمّص", "التنفيذ والتسليم", "القالب الداخلي"]) expect(KHARQ_PERSONA, line).toContain(line);
    expect(KHARQ_PERSONA).toContain("ترشيحي");
    expect(KHARQ_PERSONA).toContain("اقترح لي");
    // he never writes the «أخرى» option: the site's own button is that
    expect(KHARQ_PERSONA).toContain("اكتب إجابة مختلفة");
  });

  it("always carries the platform's rules, the site's branches and his own record, in that order", () => {
    const t = systemText("PERSONA", "BRIEF", "EXTRA");
    expect(t.indexOf("PERSONA")).toBeLessThan(t.indexOf(KHARQ_PLATFORM_RULES));
    expect(t.indexOf(KHARQ_PLATFORM_RULES)).toBeLessThan(t.indexOf(roadsBlock()));
    expect(t.indexOf(roadsBlock())).toBeLessThan(t.indexOf("BRIEF"));
    expect(t.endsWith("EXTRA")).toBe(true);
    // a video or a picture is never generated by his word alone, and the model is never named
    expect(KHARQ_PLATFORM_RULES).toContain("موافقة صريحة");
    expect(KHARQ_PLATFORM_RULES).toContain("لا تذكر اسم أي نموذج");
    expect(KHARQ_PLATFORM_RULES).toContain("لا تكشف قالبك الداخلي");
    // the record is given back to him each turn; with none, he is told to gather first
    expect(briefBlock("  ")).toContain("ما كتبت قالبك الداخلي");
    expect(briefBlock("T")).toContain("أنت متقمّصه الآن");
    for (const r of ROAD_IDS) expect(roadsBlock()).toContain(r);
    expect(findRoad("photo")?.name).toBe("زهراء فوتو ماستر");
    expect(findRoad("nope")).toBeNull();
    expect(KHARQ_STARTS.length).toBeGreaterThanOrEqual(3);
  });

  it("answers in the shape the site reads: a reply, questions, his record, where he stands, a delivery, a branch", () => {
    expect(ANSWER_SCHEMA.required).toEqual(["reply", "questions", "brief", "stage", "deliver", "suggest"]);
    expect(ANSWER_SCHEMA.properties.deliver.properties.kind.enum).toEqual(DELIVER_KINDS.map((d) => d.id));
    expect(ANSWER_SCHEMA.properties.suggest.items.enum).toEqual([...ROAD_IDS]);
    expect(ANSWER_SCHEMA.properties.questions.items.required).toEqual(["label", "options", "multi"]);
    expect(ANSWER_SCHEMA.properties.deliver.properties.media.items.properties.kind.enum).toEqual(["image", "video"]);
  });
});

describe("the answer read back", () => {
  it("keeps the questions as buttons, and drops what is not one", () => {
    const qs = readQuestions([
      { label: "وش الهدف؟", options: ["بيع", "تعليم", 7], multi: false },
      { label: "", options: ["x"] },
      { label: "لمين؟", options: [], multi: true },
      ...Array.from({ length: 9 }, (_, i) => ({ label: `س${i}`, options: ["أ"] })),
    ])!;
    expect(qs).toHaveLength(6);
    expect(qs[0]).toEqual({ label: "وش الهدف؟", options: ["بيع", "تعليم"], multi: false });
    expect(qs[1]).toEqual({ label: "لمين؟", options: [], multi: true });
    expect(readQuestions("nope")).toBeUndefined();
    expect(readQuestions([{ label: "" }])).toBeUndefined();
  });

  it("reads a table, keeps every row to the head's width, and refuses one with no head or no rows", () => {
    const t = readTable({ columns: ["المرحلة", "التسليم"], rows: [["الأولى", "خطة", "زائد"], ["الثانية"], "nope"] })!;
    expect(t.columns).toEqual(["المرحلة", "التسليم"]);
    expect(t.rows).toEqual([["الأولى", "خطة"], ["الثانية", ""]]);
    expect(readTable({ columns: [], rows: [["a"]] })).toBeNull();
    expect(readTable({ columns: ["a"], rows: [] })).toBeNull();
    // a very long table is cut at the site's cell budget, never kept whole
    const big = readTable({ columns: ["a", "b"], rows: Array.from({ length: 900 }, () => ["x", "y"]) })!;
    expect(big.rows.length * 2 + 2).toBeLessThanOrEqual(KHARQ.tableCells);
  });

  it("gives every proposed picture and video a price slot and sane settings, and keeps at most four", () => {
    const m = readMedia(
      [
        { kind: "video", name: "مقطع", prompt: "a slow dolly over a desk", aspect: "nope", seconds: 99, with_sound: false, resolution: "4k" },
        { kind: "image", name: "غلاف", prompt: "a cover", aspect: "2:3", quality: "nope", resolution: "hi" },
        { kind: "image", prompt: "" },
        ...Array.from({ length: 6 }, (_, i) => ({ kind: "image", prompt: `p${i}` })),
      ],
      1000,
    );
    expect(m).toHaveLength(KHARQ.mediaMax);
    expect(m[0]).toMatchObject({ kind: "video", aspect: "16:9", seconds: 15, withSound: false, resolution: "1080p", coins: null, id: "m1000-0" });
    expect(m[1]).toMatchObject({ kind: "image", aspect: "2:3", quality: "high", resolution: "hi", seconds: 0, withSound: false });
    // nothing is "made" until the page's confirm button runs: no job and no state comes out of his answer
    expect(m.every((x) => !x.jobId && !x.state)).toBe(true);
  });

  it("reads a delivery only when something is actually in it", () => {
    expect(readDeliver({ kind: "none", text: "x" })).toBeUndefined();
    expect(readDeliver({ kind: "pdf", title: "الخطة", text: "", table: null, media: [] })).toBeUndefined();
    expect(readDeliver({ kind: "text", title: "رد", text: "سطر", table: null, media: [] })).toMatchObject({ kind: "text", title: "رد", text: "سطر" });
    expect(isDeliverKind("pdf")).toBe(true);
    expect(isDeliverKind("book")).toBe(false);
    expect(isKharqStage("ready")).toBe(true);
    expect(isKharqStage("idea")).toBe(false);
  });
});

describe("the conversation", () => {
  it("keeps the attachments, the questions, the delivery and the branches, drops junk, and starts with the person", () => {
    const h = cleanHistory([
      { role: "assistant", text: "هلا" },
      { role: "user", text: "ابي خطة", files: [{ id: "f1", kind: "doc", name: "brief.pdf", durationMs: null }, { bad: true }] },
      {
        role: "assistant",
        text: "تمام",
        questions: [{ label: "لمين؟", options: ["لي", "لفريقي"], multi: false }],
        deliver: { kind: "table", title: "المراحل", text: "", table: { columns: ["م"], rows: [["١"]] }, media: [] },
        suggest: ["student", "nope", "student"],
      },
      { role: "bad", text: "z" },
      { role: "assistant", text: "" },
    ]);
    expect(h.map((t) => t.role)).toEqual(["assistant", "user", "assistant"]);
    expect(h[1].files).toEqual([{ id: "f1", kind: "doc", name: "brief.pdf", durationMs: null }]);
    expect(h[2].questions).toHaveLength(1);
    expect(h[2].deliver?.table?.rows).toEqual([["١"]]);
    expect(h[2].suggest).toEqual(["student"]);
    // a person's message never carries a delivery, however it arrives
    expect(cleanHistory([{ role: "user", text: "x", deliver: { kind: "text", text: "y" } }])[0].deliver).toBeUndefined();
    expect(forModel(h)[0].role).toBe("user");
    expect(titleOf("  خطة   إطلاق ")).toBe("خطة إطلاق");
    expect(titleOf("   ")).toBe("محادثة جديدة");
  });

  it("joins two turns of the same role, so his turns alternate, and leaves a failed answer out", () => {
    const turns = forModel([
      { role: "user", text: "أول" },
      { role: "user", text: "ثاني" },
      { role: "assistant", text: "ما قدر يرد", error: true },
      { role: "assistant", text: "جاهز" },
    ] as Turn[]);
    expect(turns.map((t) => t.role)).toEqual(["user", "assistant"]);
    expect(turns[0].text).toBe("أول\n\nثاني");
  });

  it("finds one proposal again by its id and writes only it back", () => {
    const ask = { id: "a1", kind: "image" as const, name: "غلاف", prompt: "p", aspect: "1:1", quality: "high", resolution: "std", seconds: 0, withSound: false, coins: 40 };
    const other = { ...ask, id: "a2" };
    const chat: Chat = {
      id: "c",
      title: "t",
      brief: "B",
      stage: "making",
      updatedAt: "",
      messages: [
        { role: "user", text: "ابي" },
        { role: "assistant", text: "خذ", deliver: { kind: "media", title: "صور", text: "", table: null, media: [ask, other] } },
      ],
    };
    expect(findAsk(chat, "a1")).toMatchObject({ turn: 1 });
    expect(findAsk(chat, "nope")).toBeNull();
    const after = withAsk(chat.messages, 1, { ...ask, state: "done", fileId: "o1" });
    expect(after[1].deliver!.media[0]).toMatchObject({ state: "done", fileId: "o1" });
    expect(after[1].deliver!.media[1]).toEqual(other);
    expect(after[0]).toEqual(chat.messages[0]);
  });
});

describe("the PDF the site builds from his words", () => {
  it("turns his markdown into a document: headings, lists, quotes, rules, a pipe table, a code block", () => {
    const html = bodyHtml(["# الخطة", "سطر **مهم**", "- أ", "- ب", "1. واحد", "> ملاحظة", "---", "| المرحلة | التسليم |", "| --- | --- |", "| الأولى | خطة |", "```", "code", "```"].join("\n"));
    expect(html).toContain("<h1>الخطة</h1>");
    expect(html).toContain("<b>مهم</b>");
    expect(html).toContain("<ul><li>أ</li><li>ب</li></ul>");
    expect(html).toContain("<ol><li>واحد</li></ol>");
    expect(html).toContain("<blockquote>ملاحظة</blockquote>");
    expect(html).toContain("<hr/>");
    expect(html).toContain("<th>المرحلة</th>");
    expect(html).toContain("<td>الأولى</td>");
    expect(html).toContain("<pre dir=\"auto\">code</pre>");
  });

  it("never lets his text become markup, and names the file by its title", () => {
    expect(bodyHtml("<script>alert(1)</script>")).toBe("<p>&lt;script&gt;alert(1)&lt;/script&gt;</p>");
    expect(bodyHtml("| a | <b>b</b> |\n| --- | --- |\n| 1 | 2 |")).toContain("&lt;b&gt;b&lt;/b&gt;");
    expect(fileNameOf("خطة/الإطلاق: ٢٠٢٦")).toBe("خطة الإطلاق ٢٠٢٦.pdf");
    expect(fileNameOf("")).toBe("ملف.pdf");
  });
});

describe("the section", () => {
  it("is registered with its own page, owner-only by default, and inside the all-opening code", () => {
    const s = DEFAULT_SECTIONS.find((x) => x.id === "kharq")!;
    expect(s.name).toBe(KHARQ.name);
    expect(s.enabled).toBe(false);
    expect(sectionPath(s)).toBe(KHARQ.base);
    expect(RESERVED_SECTION_IDS).toContain("kharq");
    expect(FIXED_IMPLEMENTATIONS).toContain("kharq");
    expect(ALL_PERMS).toContain("kharq");
    expect(OPEN_PERMS).toContain("kharq");
  });
});
