// «محمد الخارق» — the pictures and the videos he proposed, and the person's yes. Nothing is generated by his answer
// alone: the page shows each proposal with its price and a confirm button, and only a press gets here. Then جواد's
// desk makes it as an ordinary JAWAD AI job (the site's prices, the one provider key, the one ledger, and the file in
// «أعمالي»), and the follow-up moves it forward until it is ready. Server only.

import { UserError } from "@/lib/api";
import { createAdminClient } from "@/lib/supabase/admin";
import { storage } from "@/lib/storage";
import { JAWAD_BUCKET } from "@/lib/jawad/server/runtime";
import { deskCheck, deskImage, deskVideo, DeskError, type DeskWho } from "@/lib/content/jawad";
import { unlimitedFor } from "@/lib/access";
import { findAsk, getChat, saveChat, withAsk, type MediaAsk } from "./chats";

const db = () => createAdminClient();
const LINK_SECONDS = 6 * 3600;

/** A short-lived link of a file جواد made (by its output id), for the page to show and download. */
export async function outputLinks(userId: string, ids: string[]): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  const wanted = [...new Set(ids.filter(Boolean))].slice(0, 60);
  if (!wanted.length) return out;
  const { data } = await db().from("jawad_outputs").select("id,storage_path,job_id").in("id", wanted);
  const rows = (data ?? []) as { id: string; storage_path: string; job_id: string }[];
  if (!rows.length) return out;
  // only the person's own files are ever signed
  const { data: jobs } = await db().from("jawad_jobs").select("id").in("id", [...new Set(rows.map((r) => r.job_id))]).eq("user_id", userId);
  const mine = new Set(((jobs ?? []) as { id: string }[]).map((j) => j.id));
  const ours = rows.filter((r) => mine.has(r.job_id));
  if (!ours.length) return out;
  const { data: signed } = await storage.from(JAWAD_BUCKET).createSignedUrls(ours.map((r) => r.storage_path), LINK_SECONDS);
  ours.forEach((r, i) => signed?.[i]?.signedUrl && out.set(r.id, signed[i].signedUrl));
  return out;
}

const whoOf = async (userId: string, email: string | null, origin: string): Promise<DeskWho> => ({ id: userId, email, owner: await unlimitedFor(email), origin });

const reasonOf = (e: unknown) => (e instanceof DeskError ? e.reason : e instanceof UserError ? e.message : "ما قدر جواد يسوّيه الحين؛ جرّب مرة ثانية.");

/**
 * The person said yes to one proposal. A picture comes back in the same request (about a minute); a video is started
 * and followed afterwards (see `follow`). The conversation keeps where it stands either way.
 */
export async function confirm(o: { userId: string; chatId: string; askId: string; email: string | null; origin: string }): Promise<{ ask: MediaAsk; link: string | null }> {
  const chat = await getChat(o.userId, o.chatId);
  if (!chat) throw new UserError("ما لقينا هذي المحادثة.", 404);
  const found = findAsk(chat, o.askId);
  if (!found) throw new UserError("ما لقينا هذا الطلب في المحادثة.", 404);
  if (found.ask.jobId) throw new UserError("هذا الطلب بدأ من قبل.", 409);

  const req = {
    key: `kharq-${o.chatId.replace(/-/g, "").slice(0, 16)}-${found.ask.id.replace(/[^A-Za-z0-9_-]/g, "").slice(0, 24)}`,
    kind: found.ask.kind,
    prompt: found.ask.prompt,
    aspect: found.ask.aspect,
    quality: found.ask.quality,
    resolution: found.ask.resolution,
    ...(found.ask.kind === "video" ? { seconds: found.ask.seconds, withSound: found.ask.withSound } : {}),
  };
  const who = await whoOf(o.userId, o.email, o.origin);

  let ask: MediaAsk;
  try {
    if (found.ask.kind === "image") {
      const { out, receipt } = await deskImage(who, req);
      ask = { ...found.ask, jobId: receipt.jobId, state: "done", fileId: out.outputId, coins: receipt.free ? 0 : receipt.coins, status: undefined, error: undefined };
    } else {
      const receipt = await deskVideo(who, req);
      ask = { ...found.ask, jobId: receipt.jobId, state: "running", status: "بدأ التوليد", coins: receipt.free ? 0 : receipt.coins, error: undefined };
    }
  } catch (e) {
    ask = { ...found.ask, state: "failed", error: reasonOf(e) };
    await saveChat(o.userId, o.chatId, withAsk(chat.messages, found.turn, ask), 0).catch(() => null);
    throw new UserError(ask.error ?? "تعذّر التوليد.", 502);
  }
  await saveChat(o.userId, o.chatId, withAsk(chat.messages, found.turn, ask), 0);
  const link = ask.fileId ? (await outputLinks(o.userId, [ask.fileId])).get(ask.fileId) ?? null : null;
  return { ask, link };
}

/** Where a started generation stands now (a video moves forward each time this is asked). */
export async function follow(o: { userId: string; chatId: string; askId: string }): Promise<{ ask: MediaAsk; link: string | null }> {
  const chat = await getChat(o.userId, o.chatId);
  if (!chat) throw new UserError("ما لقينا هذي المحادثة.", 404);
  const found = findAsk(chat, o.askId);
  if (!found) throw new UserError("ما لقينا هذا الطلب في المحادثة.", 404);
  if (!found.ask.jobId || found.ask.state === "done" || found.ask.state === "failed") {
    const link = found.ask.fileId ? (await outputLinks(o.userId, [found.ask.fileId])).get(found.ask.fileId) ?? null : null;
    return { ask: found.ask, link };
  }
  const state = await deskCheck(o.userId, found.ask.jobId);
  const ask: MediaAsk =
    state.state === "done"
      ? { ...found.ask, state: "done", fileId: state.out.outputId, status: undefined }
      : state.state === "failed"
        ? { ...found.ask, state: "failed", error: state.error.reason }
        : { ...found.ask, state: "running", status: state.status || "قيد التوليد" };
  if (ask.state !== found.ask.state || ask.status !== found.ask.status) await saveChat(o.userId, o.chatId, withAsk(chat.messages, found.turn, ask), 0).catch(() => null);
  const link = ask.fileId ? (await outputLinks(o.userId, [ask.fileId])).get(ask.fileId) ?? null : null;
  return { ask, link };
}
