// The 24 styles from the course guide «دليل_الستايلات_24_كامل.pdf». `text` is the style text, copied verbatim;
// it is inserted unchanged into every image prompt. `tier` is reserved for future free/paid packages.

export interface FilmStyle {
  id: string;
  group: string;
  name: string;
  description: string;
  text: string;
  feel: string;
  bestFor: string;
  tier: "free" | "paid" | null;
}

export const FILM_STYLES: FilmStyle[] = [
  { id: "pixar-classic", group: "الدفء العائلي", name: "بيكسار الكلاسيكي", description: "أشكال مستديرة ودودة، أسطح ناعمة بلمعان بلاستيكي خفيف، وإضاءة مسرحية دافئة تقابلها ظلال باردة.", text: "Early Pixar 3D animation style. Clean smooth surfaces with a faint plastic sheen, simplified material variety, theatrical three-point key lighting with crisp falloff, warm key against cool fill, low texture noise, bright readable silhouettes, rounded friendly shape language.", feel: "لعب · براءة · أمان", bestFor: "قصص أطفال · شخصيات جامدة تنبض بالحياة", tier: null },
  { id: "pixar-caricature", group: "الدفء العائلي", name: "بيكسار الكاريكاتيرية", description: "نسب كاريكاتيرية بطولية داخل بيئة واقعية، خامات مفصلة، إضاءة سينمائية دافئة، وعمق ميدان ضحل.", text: "Pixar caricatured realism. Stylized heroic proportions with broadened shoulders and simplified hands, set inside a physically believable environment. Realistic cloth, leather and metal response, soft subsurface scattering, meticulous groom detail, warm cinematic color grade, shallow depth of field.", feel: "صدق · ألفة · تعاطف", bestFor: "دراما عائلية · رحلة بطل عادي", tier: null },
  { id: "illumination", group: "الدفء العائلي", name: "إلومينيشن", description: "أشكال مستديرة مبسطة وسهلة القراءة، أسطح نظيفة، ألوان مشبعة، وإضاءة ناعمة متوازنة بتباين لطيف.", text: "Illumination Entertainment 3D animation style. Rounded simplified shape language, smooth clean low-noise surfaces, broad readable forms, high-saturation color, soft even lighting with gentle contrast, reduced detail density, friendly accessible rendering.", feel: "خفة · مرح · بساطة", bestFor: "كوميديا جماهيرية · محتوى سريع", tier: null },
  { id: "neo-disney", group: "الدفء العائلي", name: "النيو-ديزني 3D", description: "تصيير ثلاثي الأبعاد بملمس لوحي، إضاءة متلألئة بألوان الأحجار الكريمة، أقمشة انسيابية، وزخارف دقيقة مع ذرات عائمة.", text: "Modern Walt Disney Animation Studios 3D. Painterly CG with softened edges, luminous color bounce, jewel-toned art-directed lighting favoring beauty over physical accuracy, elegant flowing cloth simulation, ornamental embroidery and trim detail, fine drifting particles in the air.", feel: "انبهار · حلم · رومانسية", bestFor: "حكاية سحرية · بطولة أنثوية", tier: null },
  { id: "pixar-natural", group: "الوقار الملحمي", name: "بيكسار الطبيعية", description: "محاكاة طبيعية دقيقة للماء والمواد، انكسارات ضوئية وقطرات، خامات رطبة، وضباب جوي بألوان هادئة.", text: "Pixar naturalistic simulation. Heavy physically accurate simulation with refraction, caustics, surface tension and micro-droplets clinging to surfaces. Photographic environment lighting, atmospheric haze, damp realistic textures, muted naturalistic palette, believable weight in every material.", feel: "رهبة الطبيعة · واقعية", bestFor: "مشاهد عناصر · ماء ونار وعاصفة", tier: null },
  { id: "dreamworks-epic", group: "الوقار الملحمي", name: "دريم ووركس الملحمي", description: "تكوينات سينمائية واسعة، خلفيات بروح الرسم بالحبر، إضاءة حواف درامية، وشخصيات ذات وزن وحضور.", text: "DreamWorks epic style, Kung Fu Panda lineage. Cinematic wide-scale staging, rich ink-wash inspired background painting, dramatic rim lighting and volumetric haze, stylized but weighty character rendering, ornamental costume detail, sweeping camera language.", feel: "جلال · شرف · تصاعد", bestFor: "معارك · أساطير شرقية", tier: null },
  { id: "shinkai", group: "الوقار الملحمي", name: "شينكاي", description: "خلفيات مرسومة فائقة التفصيل، سماوات ومياه متوهجة، وهج عدسات، وزرقة عميقة بلمسات دافئة رومانسية.", text: "Makoto Shinkai style anime. Hyper-detailed photoreal painted backgrounds, extreme sky and water rendering, prominent lens flares, light scattering and bloom, deep saturated blues with glowing warm accents, glass-like reflective surfaces, romantic luminous atmosphere.", feel: "شوق · جمال موجع", bestFor: "لحظة تأمل تحت سماء هائلة", tier: null },
  { id: "seinen", group: "الوقار الملحمي", name: "سايبربانك / ساينن", description: "نسب واقعية وتفاصيل معمارية دقيقة، خامات صناعية محببة، ألوان باردة خافتة، وإضاءة مسطحة هادئة.", text: "Seinen anime, Ghost in the Shell lineage. Detailed realistic proportions, restrained muted cold palette, heavy industrial texture and film grain, subdued flat lighting, slow deliberate pacing, grounded adult tone, architectural background precision.", feel: "عزلة · ثقل · وحدة", bestFor: "عالم بارد · سلطة وقهر", tier: null },
  { id: "dreamworks-painterly", group: "اللمسة اليدوية", name: "دريم ووركس اللوحي", description: "ضربات فرشاة وخامات جافة فوق مجسمات، حواف مرسومة، تباين مرتفع، وأشكال زاوية بحركة متدرجة.", text: "DreamWorks painterly style. Visible brush strokes and dry-media texture layered over 3D forms, hand-painted highlight shapes, graphic edge lines on the silhouette, stepped animation on 2s and 3s, heightened contrast, bold angular shape language.", feel: "حرفية · أصالة · دفء", bestFor: "حكاية تراثية بروح معاصرة", tier: null },
  { id: "hybrid-2d3d", group: "اللمسة اليدوية", name: "الهجين 2D/3D", description: "مجسمات تحمل خطوطًا يدوية متغيرة، تظليل بقوام قلم الرصاص، ولوحة شبه أحادية بلمسة لونية.", text: "Hybrid 2D-over-3D animation, Paperman style. Three-dimensional forms carrying hand-drawn expressive contour lines that breathe and vary in weight. Near-monochrome palette with a single color accent, soft pencil-texture shading, visible drawn imperfection over precise geometry.", feel: "حنين · رقة · خصوصية", bestFor: "لحظة شاعرية قصيرة", tier: null },
  { id: "drawn-over-cg", group: "اللمسة اليدوية", name: "المرسوم فوق CG", description: "خطوط اسكتش وخربشات فوق مجسمات، إضاءات مرسومة، طبقات ورقية، وروح ألبوم قصاصات بعفوية مقصودة.", text: "Hand-drawn-over-CG animation, Mitchells vs The Machines style. Rough sketch lines, scribbled hatch marks and hand-painted light shapes layered on top of 3D geometry, slightly imperfect registration, illustrated scrapbook energy, textured paper overlay, doodle accents.", feel: "عفوية · صدق · قرب", bestFor: "محتوى شبابي · مذكرات", tier: null },
  { id: "golden-2d", group: "اللمسة اليدوية", name: "العصر الذهبي 2D", description: "شخصيات مرسومة بالحبر وألوان مسطحة، خلفيات مائية بحبيبات ورق ظاهرة، ونبرة فيلم قديم دافئة.", text: "Classic hand-drawn 2D animation, golden-age Disney. Ink-and-paint cel characters with soft grease-pencil line weight, flat gouache color fills, lush watercolor painted backgrounds with visible paper grain, full animation on 1s, warm vintage film tone, gentle vignetting.", feel: "حنين · طفولة · تراث", bestFor: "حدوتة كلاسيكية", tier: null },
  { id: "ghibli", group: "الهدوء التأملي", name: "جيبلي", description: "خلفيات مائية ناعمة وعميقة، خطوط لطيفة، ألوان طبيعية مخفوضة، ومساحات ساكنة واسعة بإحساس دافئ.", text: "Studio Ghibli style hand-drawn 2D animation. Soft watercolor painted backgrounds with atmospheric depth, gentle consistent line weight, muted natural palette, restrained realistic movement, generous still framing and quiet negative space, warm analog film feel.", feel: "سكينة · صفاء · امتنان", bestFor: "حياة يومية · طبيعة · طفولة", tier: null },
  { id: "pixar-abstract", group: "الهدوء التأملي", name: "بيكسار التجريدي", description: "فراغ رمزي بلا أفق أو عمارة، ذرات ضوء عائمة، خامات شفافة متوهجة، ومقياس حالم.", text: "Pixar conceptual abstraction. Environment reduced to symbolic essentials with no horizon and no background architecture, only void and soft floating light motes. Materials simplified to glowing translucency, ethereal non-literal space, minimal palette, dreamlike scale.", feel: "تجرّد · دهشة · غموض", bestFor: "عالم داخلي · روح · ذاكرة", tier: null },
  { id: "comic-print", group: "الطاقة البصرية", name: "الكوميكس المطبوع", description: "تظليل بنقاط طباعة، حواف مفصولة لونيًا، خطوط سرعة وحبر، وكتل لونية جريئة بمحاذاة مطبعية منحرفة.", text: "Spider-Verse graphic print style. Halftone dot shading in shadow zones, chromatic aberration split on high-contrast edges, hand-drawn line work and speed-line accents, variable frame rate mixing 1s and 2s, print-registration misalignment, flat bold color blocking, comic ink texture.", feel: "اندفاع · صدمة · شباب", bestFor: "أكشن · افتتاحية · هوية جريئة", tier: null },
  { id: "modern-shonen", group: "الطاقة البصرية", name: "شونين حديث", description: "شخصيات بحدود حبر واضحة وظلال حادة، بيئات مفصلة، أشعة ضوء وجسيمات، وكاميرا ديناميكية درامية.", text: "Modern ufotable style anime. Cel-shaded characters with crisp ink outlines and hard-edged shadow shapes composited over detailed painted 3D environments, heavy digital compositing, volumetric light shafts, floating particles, glow bloom, dramatic color script, dynamic camera.", feel: "تصاعد · حماس · قوة", bestFor: "معركة · لحظة انفجار", tier: null },
  { id: "anime-western", group: "الطاقة البصرية", name: "الهجين الأنمي-غربي", description: "تظليل أنمي ووضعيات تعبيرية فوق مجسمات غربية، ظلال حادة، ولمسات نيون ولمعان وسط العتمة.", text: "Western-anime hybrid animation, KPop Demon Hunters lineage. Anime-derived cel shading and expressive posing fused with Western 3D craft, sharp graphic shadow shapes, neon-adjacent color accents against deep darkness, snappy stylized timing, glossy highlight punctuation.", feel: "بريق · حداثة · جاذبية", bestFor: "موسيقى · ترند · إعلان", tier: null },
  { id: "dreamworks-satire", group: "الطاقة البصرية", name: "دريم ووركس الساخر", description: "نسب زاوية مبالغ فيها، وضعيات قوية واضحة، إضاءة كوميدية متباينة، وخامات لامعة بألوان مشبعة.", text: "DreamWorks caricature 3D animation. Exaggerated angular proportions, strong pose-driven silhouettes, high-contrast comedic lighting, glossy stylized materials, punchy saturated palette, snappy exaggerated timing.", feel: "ذكاء · سخرية · جرأة", bestFor: "كوميديا ساخرة", tier: null },
  { id: "retro-cel", group: "التوقيع الشخصي", name: "ريترو سِل", description: "ألوان مرسومة على السِل بملمس ظاهر، حبيبات فيلم دافئة، نزف لوني، وإحساس بث تلفزيوني قديم.", text: "Retro hand-painted cel anime, 1980s-90s. Visible paint texture on cel surfaces, slightly off-register color, warm film grain and halation, limited animation on 3s, analog color bleed, vintage broadcast palette, soft scanline feel.", feel: "نوستالجيا · دفء قديم", bestFor: "استحضار زمن بعينه", tier: null },
  { id: "3dcg-anime", group: "التوقيع الشخصي", name: "3DCG أنمي", description: "مجسمات بظلال سِل مسطحة وحدود نظيفة، أسطح بلورية عاكسة، تفاصيل هندسية دقيقة، وكاميرا انسيابية.", text: "3DCG anime with toon shading. Three-dimensional models rendered with flat banded cel shadows and clean outline passes, crystalline reflective surfaces, precise geometric detail, smooth continuous camera movement impossible in hand-drawn 2D.", feel: "غرابة · دقة · برود", bestFor: "خيال علمي · كائنات بلورية", tier: null },
  { id: "auteur", group: "التوقيع الشخصي", name: "تجريبي / مؤلف", description: "منظور مشوّه وخطوط غير مستقرة، رسم تعبيري خام، ألوان محدودة متباينة، وخلفيات تجريدية رمزية.", text: "Auteur experimental anime. Distorted perspective and unstable line work, raw expressive drawing that shifts between frames, limited high-contrast palette, abstract symbolic background treatment, unconventional broken timing.", feel: "اضطراب · حرية · صدمة", bestFor: "فن · رسالة شخصية", tier: null },
  { id: "stylistic-drift", group: "التوقيع الشخصي", name: "الانحراف الأسلوبي", description: "تشويه متعمد بروح الأنمي، أشكال مضغوطة مبالغ فيها، تظليل مسطح، وألوان قوية مع إضاءة سينمائية.", text: "Modern stylized Pixar. Deliberate anime-influenced distortion, exaggerated squash in the shapes, flatter shading ramps, punchier saturated color, graphic simplification of secondary detail, expressive posing, cinematic lighting retained.", feel: "عصرية · تمرّد", bestFor: "جيل شاب · هوية مختلطة", tier: null },
  { id: "chibi", group: "التوقيع الشخصي", name: "موي / تشيبي", description: "رؤوس كبيرة وأجسام مختصرة بنسب صغيرة، حدود سميكة ناعمة، ألوان باستيل، وتظليل لطيف قليل التفاصيل.", text: "Chibi anime style. Compressed two-to-three-head proportions, oversized head and simplified body, thick soft outlines, pastel palette, flat gentle shading, minimal detail, cute rounded forms.", feel: "ظرافة · لعب", bestFor: "محتوى خفيف · ملصقات", tier: null },
  { id: "renaissance-90s", group: "الصقل الاحتفالي", name: "نهضة التسعينات", description: "رسم شخصيات تعبيري، تكوين وإضاءة مسرحيان، ألوان غنية مشبعة، وتوهج فوق خلفيات متعددة الطبقات.", text: "Disney Renaissance 2D animation. Bold expressive character draftsmanship, dramatic theatrical staging and lighting, rich saturated color keys, airbrushed glow effects composited over cel art, multiplane painted backgrounds with layered depth.", feel: "فخامة · شجن · مسرح", bestFor: "لحظة غنائية · ذروة عاطفية", tier: null },
];

export const findStyle = (id: string) => FILM_STYLES.find((s) => s.id === id);

/** The style's picture from the course guide (public/film/styles, one per style, 640×360). */
export const styleImage = (id: string) => `/film/styles/${id}.jpg`;
